[package]
name = "klif-telemetry"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
klif-common = { path = "../klif-common" }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
regex.workspace = true
ureq.workspace = true
windows = { workspace = true, features = [
  "Win32_Devices_DeviceAndDriverInstallation",
  "Win32_Devices_Properties",
  "Win32_Foundation",
  "Win32_Graphics_Dxgi",
  "Win32_Graphics_Dxgi_Common",
  "Win32_System_Performance",
  "Win32_System_SystemInformation",
  "Win32_System_Registry",
] }
